### ISSUE TITLE
Remove repo maintainer

### ISSUE THREAD

**Issue by 0x3639** [zenon-network/zenon.network#18]
I would like to propose the removal of mehowz as a maintainer of this repo given his recent actions in telegram towards other community members.  In addition, I do not believe he can objectively maintain this repo given his objection to its content as stated in Telegram and the .org forum.   

Unless the other maintainers of this repo object I would like to complete the removal in one week from today.  

https://t.me/zenonnetwork/365141

**Comment by mehowz** [comment]
@ whoever will make this decision. I've been actively contributing to the repo since I've been given maintainer status. A few here are finding it difficult in Telegram because I'm actively arguing against the case that network-assets like TG, Telegram, primary website representing Zenon, are network-owned assets and should be governed by the network (which is not a few admins in TG). Some owners/admins/maintainers believe that they decide on behalf of the network, and I think that's a slippery slope going forward. There are many more participants then just the few figure heads who made themselves the new owners of Zenon. The is the primary reason why I left from contributing at TC. Few people paraded that it was a community-owned/organized initiative, yet they controlled all channels and silenced at their own will. Only recently did the TC founder doxx himself and admitted he was acting on behalf of multiple alts, maintaining the TC handle etc. This is where Zenon seems to be headed. And therefore I propose new network-governance structures:

https://forum.zenon.org/t/network-governance-brainstorming/1878/35

My arguments about another topic should not warrant my performance in the repo. That's pretty clear.

Let's build a proper democracy.

**Comment by mehowz** [comment]
You guys should read what Brat and the bunch are arguing here: https://t.me/zenonnetwork/365231

**Comment by mehowz** [comment]
They literally think that because Deez became an owner of TG, that he and a few have the deciding vote on what now becomes the community domain. No democracy, nothing. Just a few calling the shots with their influence. You know what that's called? That's called figure heads. Dangerous.
